#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAODLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDL")]
	public partial class QLDLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertCTPX(CTPX instance);
    partial void UpdateCTPX(CTPX instance);
    partial void DeleteCTPX(CTPX instance);
    partial void InsertDAILY(DAILY instance);
    partial void UpdateDAILY(DAILY instance);
    partial void DeleteDAILY(DAILY instance);
    partial void InsertDVT(DVT instance);
    partial void UpdateDVT(DVT instance);
    partial void DeleteDVT(DVT instance);
    partial void InsertLOAIDL(LOAIDL instance);
    partial void UpdateLOAIDL(LOAIDL instance);
    partial void DeleteLOAIDL(LOAIDL instance);
    partial void InsertMATHANG(MATHANG instance);
    partial void UpdateMATHANG(MATHANG instance);
    partial void DeleteMATHANG(MATHANG instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertQUAN(QUAN instance);
    partial void UpdateQUAN(QUAN instance);
    partial void DeleteQUAN(QUAN instance);
    partial void InsertPHIEUXUATHANG(PHIEUXUATHANG instance);
    partial void UpdatePHIEUXUATHANG(PHIEUXUATHANG instance);
    partial void DeletePHIEUXUATHANG(PHIEUXUATHANG instance);
    partial void InsertPHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void UpdatePHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void DeletePHIEUTHUTIEN(PHIEUTHUTIEN instance);
    #endregion
		
		public QLDLDataContext() : 
				base(global::DAODLL.Properties.Settings.Default.QLDLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<CTPX> CTPXes
		{
			get
			{
				return this.GetTable<CTPX>();
			}
		}
		
		public System.Data.Linq.Table<DAILY> DAILies
		{
			get
			{
				return this.GetTable<DAILY>();
			}
		}
		
		public System.Data.Linq.Table<DVT> DVTs
		{
			get
			{
				return this.GetTable<DVT>();
			}
		}
		
		public System.Data.Linq.Table<LOAIDL> LOAIDLs
		{
			get
			{
				return this.GetTable<LOAIDL>();
			}
		}
		
		public System.Data.Linq.Table<MATHANG> MATHANGs
		{
			get
			{
				return this.GetTable<MATHANG>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<QUAN> QUANs
		{
			get
			{
				return this.GetTable<QUAN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUXUATHANG> PHIEUXUATHANGs
		{
			get
			{
				return this.GetTable<PHIEUXUATHANG>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTHUTIEN> PHIEUTHUTIENs
		{
			get
			{
				return this.GetTable<PHIEUTHUTIEN>();
			}
		}
		
		public System.Data.Linq.Table<vwCHUCVU_NHANVIEN_TAIKHOAN> vwCHUCVU_NHANVIEN_TAIKHOANs
		{
			get
			{
				return this.GetTable<vwCHUCVU_NHANVIEN_TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<vwDAILY_PHIEUTHUTIEN_NHANVIEN> vwDAILY_PHIEUTHUTIEN_NHANVIENs
		{
			get
			{
				return this.GetTable<vwDAILY_PHIEUTHUTIEN_NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<vw_SEARCH_PHIEUXUATHANG> vw_SEARCH_PHIEUXUATHANGs
		{
			get
			{
				return this.GetTable<vw_SEARCH_PHIEUXUATHANG>();
			}
		}
		
		public System.Data.Linq.Table<vwDAILY_LOAIDL_QUAN> vwDAILY_LOAIDL_QUANs
		{
			get
			{
				return this.GetTable<vwDAILY_LOAIDL_QUAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACHUCVU;
		
		private string _TENCHUCVU;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUCVUChanging(int value);
    partial void OnMACHUCVUChanged();
    partial void OnTENCHUCVUChanging(string value);
    partial void OnTENCHUCVUChanged();
    #endregion
		
		public CHUCVU()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCVU", DbType="VarChar(30)")]
		public string TENCHUCVU
		{
			get
			{
				return this._TENCHUCVU;
			}
			set
			{
				if ((this._TENCHUCVU != value))
				{
					this.OnTENCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._TENCHUCVU = value;
					this.SendPropertyChanged("TENCHUCVU");
					this.OnTENCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_NHANVIENs", ThisKey="MACHUCVU", OtherKey="MACHUCVU")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPX")]
	public partial class CTPX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPHIEU;
		
		private int _MAHANG;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntityRef<MATHANG> _MATHANG;
		
		private EntityRef<PHIEUXUATHANG> _PHIEUXUATHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUChanging(int value);
    partial void OnMAPHIEUChanged();
    partial void OnMAHANGChanging(int value);
    partial void OnMAHANGChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public CTPX()
		{
			this._MATHANG = default(EntityRef<MATHANG>);
			this._PHIEUXUATHANG = default(EntityRef<PHIEUXUATHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAPHIEU
		{
			get
			{
				return this._MAPHIEU;
			}
			set
			{
				if ((this._MAPHIEU != value))
				{
					if (this._PHIEUXUATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHIEUChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEU = value;
					this.SendPropertyChanged("MAPHIEU");
					this.OnMAPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHANG", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAHANG
		{
			get
			{
				return this._MAHANG;
			}
			set
			{
				if ((this._MAHANG != value))
				{
					if (this._MATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHANGChanging(value);
					this.SendPropertyChanging();
					this._MAHANG = value;
					this.SendPropertyChanged("MAHANG");
					this.OnMAHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATHANG_CTPX", Storage="_MATHANG", ThisKey="MAHANG", OtherKey="MAHANG", IsForeignKey=true)]
		public MATHANG MATHANG
		{
			get
			{
				return this._MATHANG.Entity;
			}
			set
			{
				MATHANG previousValue = this._MATHANG.Entity;
				if (((previousValue != value) 
							|| (this._MATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATHANG.Entity = null;
						previousValue.CTPXes.Remove(this);
					}
					this._MATHANG.Entity = value;
					if ((value != null))
					{
						value.CTPXes.Add(this);
						this._MAHANG = value.MAHANG;
					}
					else
					{
						this._MAHANG = default(int);
					}
					this.SendPropertyChanged("MATHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUXUATHANG_CTPX", Storage="_PHIEUXUATHANG", ThisKey="MAPHIEU", OtherKey="MAPHIEU", IsForeignKey=true)]
		public PHIEUXUATHANG PHIEUXUATHANG
		{
			get
			{
				return this._PHIEUXUATHANG.Entity;
			}
			set
			{
				PHIEUXUATHANG previousValue = this._PHIEUXUATHANG.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUXUATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUXUATHANG.Entity = null;
						previousValue.CTPXes.Remove(this);
					}
					this._PHIEUXUATHANG.Entity = value;
					if ((value != null))
					{
						value.CTPXes.Add(this);
						this._MAPHIEU = value.MAPHIEU;
					}
					else
					{
						this._MAPHIEU = default(int);
					}
					this.SendPropertyChanged("PHIEUXUATHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DAILY")]
	public partial class DAILY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADL;
		
		private string _TENDL;
		
		private System.Nullable<int> _LOAIDL;
		
		private string _DIENTHOAI;
		
		private string _DIACHI;
		
		private System.Nullable<int> _MAQUAN;
		
		private System.Nullable<System.DateTime> _NGAYTIEPNHAN;
		
		private System.Nullable<decimal> _SONO;
		
		private System.Nullable<int> _TINHTRANG;
		
		private EntityRef<PHIEUXUATHANG> _PHIEUXUATHANG;
		
		private EntitySet<PHIEUTHUTIEN> _PHIEUTHUTIENs;
		
		private EntityRef<LOAIDL> _LOAIDL1;
		
		private EntityRef<QUAN> _QUAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADLChanging(int value);
    partial void OnMADLChanged();
    partial void OnTENDLChanging(string value);
    partial void OnTENDLChanged();
    partial void OnLOAIDLChanging(System.Nullable<int> value);
    partial void OnLOAIDLChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnMAQUANChanging(System.Nullable<int> value);
    partial void OnMAQUANChanged();
    partial void OnNGAYTIEPNHANChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTIEPNHANChanged();
    partial void OnSONOChanging(System.Nullable<decimal> value);
    partial void OnSONOChanged();
    partial void OnTINHTRANGChanging(System.Nullable<int> value);
    partial void OnTINHTRANGChanged();
    #endregion
		
		public DAILY()
		{
			this._PHIEUXUATHANG = default(EntityRef<PHIEUXUATHANG>);
			this._PHIEUTHUTIENs = new EntitySet<PHIEUTHUTIEN>(new Action<PHIEUTHUTIEN>(this.attach_PHIEUTHUTIENs), new Action<PHIEUTHUTIEN>(this.detach_PHIEUTHUTIENs));
			this._LOAIDL1 = default(EntityRef<LOAIDL>);
			this._QUAN = default(EntityRef<QUAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADL
		{
			get
			{
				return this._MADL;
			}
			set
			{
				if ((this._MADL != value))
				{
					this.OnMADLChanging(value);
					this.SendPropertyChanging();
					this._MADL = value;
					this.SendPropertyChanged("MADL");
					this.OnMADLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDL", DbType="NVarChar(50)")]
		public string TENDL
		{
			get
			{
				return this._TENDL;
			}
			set
			{
				if ((this._TENDL != value))
				{
					this.OnTENDLChanging(value);
					this.SendPropertyChanging();
					this._TENDL = value;
					this.SendPropertyChanged("TENDL");
					this.OnTENDLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIDL", DbType="Int")]
		public System.Nullable<int> LOAIDL
		{
			get
			{
				return this._LOAIDL;
			}
			set
			{
				if ((this._LOAIDL != value))
				{
					if (this._LOAIDL1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLOAIDLChanging(value);
					this.SendPropertyChanging();
					this._LOAIDL = value;
					this.SendPropertyChanged("LOAIDL");
					this.OnLOAIDLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(50)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAQUAN", DbType="Int")]
		public System.Nullable<int> MAQUAN
		{
			get
			{
				return this._MAQUAN;
			}
			set
			{
				if ((this._MAQUAN != value))
				{
					if (this._QUAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAQUANChanging(value);
					this.SendPropertyChanging();
					this._MAQUAN = value;
					this.SendPropertyChanged("MAQUAN");
					this.OnMAQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTIEPNHAN", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTIEPNHAN
		{
			get
			{
				return this._NGAYTIEPNHAN;
			}
			set
			{
				if ((this._NGAYTIEPNHAN != value))
				{
					this.OnNGAYTIEPNHANChanging(value);
					this.SendPropertyChanging();
					this._NGAYTIEPNHAN = value;
					this.SendPropertyChanged("NGAYTIEPNHAN");
					this.OnNGAYTIEPNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SONO
		{
			get
			{
				return this._SONO;
			}
			set
			{
				if ((this._SONO != value))
				{
					this.OnSONOChanging(value);
					this.SendPropertyChanging();
					this._SONO = value;
					this.SendPropertyChanged("SONO");
					this.OnSONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="Int")]
		public System.Nullable<int> TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_PHIEUXUATHANG", Storage="_PHIEUXUATHANG", ThisKey="MADL", OtherKey="MAPHIEU", IsUnique=true, IsForeignKey=false)]
		public PHIEUXUATHANG PHIEUXUATHANG
		{
			get
			{
				return this._PHIEUXUATHANG.Entity;
			}
			set
			{
				PHIEUXUATHANG previousValue = this._PHIEUXUATHANG.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUXUATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUXUATHANG.Entity = null;
						previousValue.DAILY = null;
					}
					this._PHIEUXUATHANG.Entity = value;
					if ((value != null))
					{
						value.DAILY = this;
					}
					this.SendPropertyChanged("PHIEUXUATHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_PHIEUTHUTIEN", Storage="_PHIEUTHUTIENs", ThisKey="MADL", OtherKey="MADL")]
		public EntitySet<PHIEUTHUTIEN> PHIEUTHUTIENs
		{
			get
			{
				return this._PHIEUTHUTIENs;
			}
			set
			{
				this._PHIEUTHUTIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDL_DAILY", Storage="_LOAIDL1", ThisKey="LOAIDL", OtherKey="MALOAI", IsForeignKey=true)]
		public LOAIDL LOAIDL1
		{
			get
			{
				return this._LOAIDL1.Entity;
			}
			set
			{
				LOAIDL previousValue = this._LOAIDL1.Entity;
				if (((previousValue != value) 
							|| (this._LOAIDL1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIDL1.Entity = null;
						previousValue.DAILies.Remove(this);
					}
					this._LOAIDL1.Entity = value;
					if ((value != null))
					{
						value.DAILies.Add(this);
						this._LOAIDL = value.MALOAI;
					}
					else
					{
						this._LOAIDL = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAIDL1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUAN_DAILY", Storage="_QUAN", ThisKey="MAQUAN", OtherKey="MAQUAN", IsForeignKey=true)]
		public QUAN QUAN
		{
			get
			{
				return this._QUAN.Entity;
			}
			set
			{
				QUAN previousValue = this._QUAN.Entity;
				if (((previousValue != value) 
							|| (this._QUAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUAN.Entity = null;
						previousValue.DAILies.Remove(this);
					}
					this._QUAN.Entity = value;
					if ((value != null))
					{
						value.DAILies.Add(this);
						this._MAQUAN = value.MAQUAN;
					}
					else
					{
						this._MAQUAN = default(Nullable<int>);
					}
					this.SendPropertyChanged("QUAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = this;
		}
		
		private void detach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.DAILY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DVT")]
	public partial class DVT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADVT;
		
		private string _DVT1;
		
		private EntitySet<MATHANG> _MATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADVTChanging(int value);
    partial void OnMADVTChanged();
    partial void OnDVT1Changing(string value);
    partial void OnDVT1Changed();
    #endregion
		
		public DVT()
		{
			this._MATHANGs = new EntitySet<MATHANG>(new Action<MATHANG>(this.attach_MATHANGs), new Action<MATHANG>(this.detach_MATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADVT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADVT
		{
			get
			{
				return this._MADVT;
			}
			set
			{
				if ((this._MADVT != value))
				{
					this.OnMADVTChanging(value);
					this.SendPropertyChanging();
					this._MADVT = value;
					this.SendPropertyChanged("MADVT");
					this.OnMADVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DVT", Storage="_DVT1", DbType="NVarChar(50)")]
		public string DVT1
		{
			get
			{
				return this._DVT1;
			}
			set
			{
				if ((this._DVT1 != value))
				{
					this.OnDVT1Changing(value);
					this.SendPropertyChanging();
					this._DVT1 = value;
					this.SendPropertyChanged("DVT1");
					this.OnDVT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DVT_MATHANG", Storage="_MATHANGs", ThisKey="MADVT", OtherKey="MADVT")]
		public EntitySet<MATHANG> MATHANGs
		{
			get
			{
				return this._MATHANGs;
			}
			set
			{
				this._MATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MATHANGs(MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DVT = this;
		}
		
		private void detach_MATHANGs(MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.DVT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIDL")]
	public partial class LOAIDL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOAI;
		
		private string _TENLOAI;
		
		private System.Nullable<decimal> _SONOTOIDA;
		
		private EntitySet<DAILY> _DAILies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIChanging(int value);
    partial void OnMALOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    partial void OnSONOTOIDAChanging(System.Nullable<decimal> value);
    partial void OnSONOTOIDAChanged();
    #endregion
		
		public LOAIDL()
		{
			this._DAILies = new EntitySet<DAILY>(new Action<DAILY>(this.attach_DAILies), new Action<DAILY>(this.detach_DAILies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(10)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONOTOIDA", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SONOTOIDA
		{
			get
			{
				return this._SONOTOIDA;
			}
			set
			{
				if ((this._SONOTOIDA != value))
				{
					this.OnSONOTOIDAChanging(value);
					this.SendPropertyChanging();
					this._SONOTOIDA = value;
					this.SendPropertyChanged("SONOTOIDA");
					this.OnSONOTOIDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDL_DAILY", Storage="_DAILies", ThisKey="MALOAI", OtherKey="LOAIDL")]
		public EntitySet<DAILY> DAILies
		{
			get
			{
				return this._DAILies;
			}
			set
			{
				this._DAILies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAILies(DAILY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDL1 = this;
		}
		
		private void detach_DAILies(DAILY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDL1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATHANG")]
	public partial class MATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHANG;
		
		private string _TENHANG;
		
		private System.Nullable<int> _MADVT;
		
		private System.Nullable<decimal> _DONGIA;
		
		private EntitySet<CTPX> _CTPXes;
		
		private EntityRef<DVT> _DVT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHANGChanging(int value);
    partial void OnMAHANGChanged();
    partial void OnTENHANGChanging(string value);
    partial void OnTENHANGChanged();
    partial void OnMADVTChanging(System.Nullable<int> value);
    partial void OnMADVTChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    #endregion
		
		public MATHANG()
		{
			this._CTPXes = new EntitySet<CTPX>(new Action<CTPX>(this.attach_CTPXes), new Action<CTPX>(this.detach_CTPXes));
			this._DVT = default(EntityRef<DVT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHANG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAHANG
		{
			get
			{
				return this._MAHANG;
			}
			set
			{
				if ((this._MAHANG != value))
				{
					this.OnMAHANGChanging(value);
					this.SendPropertyChanging();
					this._MAHANG = value;
					this.SendPropertyChanged("MAHANG");
					this.OnMAHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHANG", DbType="NVarChar(50)")]
		public string TENHANG
		{
			get
			{
				return this._TENHANG;
			}
			set
			{
				if ((this._TENHANG != value))
				{
					this.OnTENHANGChanging(value);
					this.SendPropertyChanging();
					this._TENHANG = value;
					this.SendPropertyChanged("TENHANG");
					this.OnTENHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADVT", DbType="Int")]
		public System.Nullable<int> MADVT
		{
			get
			{
				return this._MADVT;
			}
			set
			{
				if ((this._MADVT != value))
				{
					if (this._DVT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADVTChanging(value);
					this.SendPropertyChanging();
					this._MADVT = value;
					this.SendPropertyChanged("MADVT");
					this.OnMADVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATHANG_CTPX", Storage="_CTPXes", ThisKey="MAHANG", OtherKey="MAHANG")]
		public EntitySet<CTPX> CTPXes
		{
			get
			{
				return this._CTPXes;
			}
			set
			{
				this._CTPXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DVT_MATHANG", Storage="_DVT", ThisKey="MADVT", OtherKey="MADVT", IsForeignKey=true)]
		public DVT DVT
		{
			get
			{
				return this._DVT.Entity;
			}
			set
			{
				DVT previousValue = this._DVT.Entity;
				if (((previousValue != value) 
							|| (this._DVT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DVT.Entity = null;
						previousValue.MATHANGs.Remove(this);
					}
					this._DVT.Entity = value;
					if ((value != null))
					{
						value.MATHANGs.Add(this);
						this._MADVT = value.MADVT;
					}
					else
					{
						this._MADVT = default(Nullable<int>);
					}
					this.SendPropertyChanged("DVT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPXes(CTPX entity)
		{
			this.SendPropertyChanging();
			entity.MATHANG = this;
		}
		
		private void detach_CTPXes(CTPX entity)
		{
			this.SendPropertyChanging();
			entity.MATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANV;
		
		private string _TENNV;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _DIACHI;
		
		private int _MACHUCVU;
		
		private EntitySet<TAIKHOAN> _TAIKHOANs;
		
		private EntitySet<PHIEUXUATHANG> _PHIEUXUATHANGs;
		
		private EntitySet<PHIEUTHUTIEN> _PHIEUTHUTIENs;
		
		private EntityRef<CHUCVU> _CHUCVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(int value);
    partial void OnMANVChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnMACHUCVUChanging(int value);
    partial void OnMACHUCVUChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._TAIKHOANs = new EntitySet<TAIKHOAN>(new Action<TAIKHOAN>(this.attach_TAIKHOANs), new Action<TAIKHOAN>(this.detach_TAIKHOANs));
			this._PHIEUXUATHANGs = new EntitySet<PHIEUXUATHANG>(new Action<PHIEUXUATHANG>(this.attach_PHIEUXUATHANGs), new Action<PHIEUXUATHANG>(this.detach_PHIEUXUATHANGs));
			this._PHIEUTHUTIENs = new EntitySet<PHIEUTHUTIEN>(new Action<PHIEUTHUTIEN>(this.attach_PHIEUTHUTIENs), new Action<PHIEUTHUTIEN>(this.detach_PHIEUTHUTIENs));
			this._CHUCVU = default(EntityRef<CHUCVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NChar(10)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", DbType="Int NOT NULL")]
		public int MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					if (this._CHUCVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOAN", Storage="_TAIKHOANs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this._TAIKHOANs;
			}
			set
			{
				this._TAIKHOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUXUATHANG", Storage="_PHIEUXUATHANGs", ThisKey="MANV", OtherKey="NGUOIXUAT")]
		public EntitySet<PHIEUXUATHANG> PHIEUXUATHANGs
		{
			get
			{
				return this._PHIEUXUATHANGs;
			}
			set
			{
				this._PHIEUXUATHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUTHUTIEN", Storage="_PHIEUTHUTIENs", ThisKey="MANV", OtherKey="NGUOITHU")]
		public EntitySet<PHIEUTHUTIEN> PHIEUTHUTIENs
		{
			get
			{
				return this._PHIEUTHUTIENs;
			}
			set
			{
				this._PHIEUTHUTIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_CHUCVU", ThisKey="MACHUCVU", OtherKey="MACHUCVU", IsForeignKey=true)]
		public CHUCVU CHUCVU
		{
			get
			{
				return this._CHUCVU.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._CHUCVU.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._MACHUCVU = value.MACHUCVU;
					}
					else
					{
						this._MACHUCVU = default(int);
					}
					this.SendPropertyChanged("CHUCVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUXUATHANGs(PHIEUXUATHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUXUATHANGs(PHIEUXUATHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATK;
		
		private string _TENDANGNHAP;
		
		private string _PASSWORD;
		
		private System.Nullable<int> _MANV;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKChanging(int value);
    partial void OnMATKChanged();
    partial void OnTENDANGNHAPChanging(string value);
    partial void OnTENDANGNHAPChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnMANVChanging(System.Nullable<int> value);
    partial void OnMANVChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATK
		{
			get
			{
				return this._MATK;
			}
			set
			{
				if ((this._MATK != value))
				{
					this.OnMATKChanging(value);
					this.SendPropertyChanging();
					this._MATK = value;
					this.SendPropertyChanged("MATK");
					this.OnMATKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDANGNHAP", DbType="NChar(20)")]
		public string TENDANGNHAP
		{
			get
			{
				return this._TENDANGNHAP;
			}
			set
			{
				if ((this._TENDANGNHAP != value))
				{
					this.OnTENDANGNHAPChanging(value);
					this.SendPropertyChanging();
					this._TENDANGNHAP = value;
					this.SendPropertyChanged("TENDANGNHAP");
					this.OnTENDANGNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int")]
		public System.Nullable<int> MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOAN", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TAIKHOANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TAIKHOANs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUAN")]
	public partial class QUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAQUAN;
		
		private string _TENQUAN;
		
		private System.Nullable<int> _SODLTOIDA;
		
		private EntitySet<DAILY> _DAILies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAQUANChanging(int value);
    partial void OnMAQUANChanged();
    partial void OnTENQUANChanging(string value);
    partial void OnTENQUANChanged();
    partial void OnSODLTOIDAChanging(System.Nullable<int> value);
    partial void OnSODLTOIDAChanged();
    #endregion
		
		public QUAN()
		{
			this._DAILies = new EntitySet<DAILY>(new Action<DAILY>(this.attach_DAILies), new Action<DAILY>(this.detach_DAILies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAQUAN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAQUAN
		{
			get
			{
				return this._MAQUAN;
			}
			set
			{
				if ((this._MAQUAN != value))
				{
					this.OnMAQUANChanging(value);
					this.SendPropertyChanging();
					this._MAQUAN = value;
					this.SendPropertyChanged("MAQUAN");
					this.OnMAQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENQUAN", DbType="NVarChar(50)")]
		public string TENQUAN
		{
			get
			{
				return this._TENQUAN;
			}
			set
			{
				if ((this._TENQUAN != value))
				{
					this.OnTENQUANChanging(value);
					this.SendPropertyChanging();
					this._TENQUAN = value;
					this.SendPropertyChanged("TENQUAN");
					this.OnTENQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODLTOIDA", DbType="Int")]
		public System.Nullable<int> SODLTOIDA
		{
			get
			{
				return this._SODLTOIDA;
			}
			set
			{
				if ((this._SODLTOIDA != value))
				{
					this.OnSODLTOIDAChanging(value);
					this.SendPropertyChanging();
					this._SODLTOIDA = value;
					this.SendPropertyChanged("SODLTOIDA");
					this.OnSODLTOIDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUAN_DAILY", Storage="_DAILies", ThisKey="MAQUAN", OtherKey="MAQUAN")]
		public EntitySet<DAILY> DAILies
		{
			get
			{
				return this._DAILies;
			}
			set
			{
				this._DAILies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAILies(DAILY entity)
		{
			this.SendPropertyChanging();
			entity.QUAN = this;
		}
		
		private void detach_DAILies(DAILY entity)
		{
			this.SendPropertyChanging();
			entity.QUAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUXUATHANG")]
	public partial class PHIEUXUATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPHIEU;
		
		private System.Nullable<int> _MADL;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private System.Nullable<decimal> _TONGTIEN;
		
		private System.Nullable<decimal> _SOTIENTRA;
		
		private System.Nullable<decimal> _CONLAI;
		
		private System.Nullable<int> _NGUOIXUAT;
		
		private EntitySet<CTPX> _CTPXes;
		
		private EntityRef<DAILY> _DAILY;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUChanging(int value);
    partial void OnMAPHIEUChanged();
    partial void OnMADLChanging(System.Nullable<int> value);
    partial void OnMADLChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    partial void OnTONGTIENChanging(System.Nullable<decimal> value);
    partial void OnTONGTIENChanged();
    partial void OnSOTIENTRAChanging(System.Nullable<decimal> value);
    partial void OnSOTIENTRAChanged();
    partial void OnCONLAIChanging(System.Nullable<decimal> value);
    partial void OnCONLAIChanged();
    partial void OnNGUOIXUATChanging(System.Nullable<int> value);
    partial void OnNGUOIXUATChanged();
    #endregion
		
		public PHIEUXUATHANG()
		{
			this._CTPXes = new EntitySet<CTPX>(new Action<CTPX>(this.attach_CTPXes), new Action<CTPX>(this.detach_CTPXes));
			this._DAILY = default(EntityRef<DAILY>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEU
		{
			get
			{
				return this._MAPHIEU;
			}
			set
			{
				if ((this._MAPHIEU != value))
				{
					if (this._DAILY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHIEUChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEU = value;
					this.SendPropertyChanged("MAPHIEU");
					this.OnMAPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADL", DbType="Int")]
		public System.Nullable<int> MADL
		{
			get
			{
				return this._MADL;
			}
			set
			{
				if ((this._MADL != value))
				{
					this.OnMADLChanging(value);
					this.SendPropertyChanging();
					this._MADL = value;
					this.SendPropertyChanged("MADL");
					this.OnMADLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTIENTRA", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SOTIENTRA
		{
			get
			{
				return this._SOTIENTRA;
			}
			set
			{
				if ((this._SOTIENTRA != value))
				{
					this.OnSOTIENTRAChanging(value);
					this.SendPropertyChanging();
					this._SOTIENTRA = value;
					this.SendPropertyChanged("SOTIENTRA");
					this.OnSOTIENTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONLAI", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CONLAI
		{
			get
			{
				return this._CONLAI;
			}
			set
			{
				if ((this._CONLAI != value))
				{
					this.OnCONLAIChanging(value);
					this.SendPropertyChanging();
					this._CONLAI = value;
					this.SendPropertyChanged("CONLAI");
					this.OnCONLAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOIXUAT", DbType="Int")]
		public System.Nullable<int> NGUOIXUAT
		{
			get
			{
				return this._NGUOIXUAT;
			}
			set
			{
				if ((this._NGUOIXUAT != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNGUOIXUATChanging(value);
					this.SendPropertyChanging();
					this._NGUOIXUAT = value;
					this.SendPropertyChanged("NGUOIXUAT");
					this.OnNGUOIXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUXUATHANG_CTPX", Storage="_CTPXes", ThisKey="MAPHIEU", OtherKey="MAPHIEU")]
		public EntitySet<CTPX> CTPXes
		{
			get
			{
				return this._CTPXes;
			}
			set
			{
				this._CTPXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_PHIEUXUATHANG", Storage="_DAILY", ThisKey="MAPHIEU", OtherKey="MADL", IsForeignKey=true)]
		public DAILY DAILY
		{
			get
			{
				return this._DAILY.Entity;
			}
			set
			{
				DAILY previousValue = this._DAILY.Entity;
				if (((previousValue != value) 
							|| (this._DAILY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DAILY.Entity = null;
						previousValue.PHIEUXUATHANG = null;
					}
					this._DAILY.Entity = value;
					if ((value != null))
					{
						value.PHIEUXUATHANG = this;
						this._MAPHIEU = value.MADL;
					}
					else
					{
						this._MAPHIEU = default(int);
					}
					this.SendPropertyChanged("DAILY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUXUATHANG", Storage="_NHANVIEN", ThisKey="NGUOIXUAT", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUXUATHANGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUXUATHANGs.Add(this);
						this._NGUOIXUAT = value.MANV;
					}
					else
					{
						this._NGUOIXUAT = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPXes(CTPX entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUXUATHANG = this;
		}
		
		private void detach_CTPXes(CTPX entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUXUATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTHUTIEN")]
	public partial class PHIEUTHUTIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPHIEU;
		
		private System.Nullable<int> _MADL;
		
		private System.Nullable<System.DateTime> _NGAYTHUTIEN;
		
		private System.Nullable<decimal> _SOTIEN;
		
		private System.Nullable<int> _NGUOITHU;
		
		private EntityRef<DAILY> _DAILY;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUChanging(int value);
    partial void OnMAPHIEUChanged();
    partial void OnMADLChanging(System.Nullable<int> value);
    partial void OnMADLChanged();
    partial void OnNGAYTHUTIENChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHUTIENChanged();
    partial void OnSOTIENChanging(System.Nullable<decimal> value);
    partial void OnSOTIENChanged();
    partial void OnNGUOITHUChanging(System.Nullable<int> value);
    partial void OnNGUOITHUChanged();
    #endregion
		
		public PHIEUTHUTIEN()
		{
			this._DAILY = default(EntityRef<DAILY>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEU
		{
			get
			{
				return this._MAPHIEU;
			}
			set
			{
				if ((this._MAPHIEU != value))
				{
					this.OnMAPHIEUChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEU = value;
					this.SendPropertyChanged("MAPHIEU");
					this.OnMAPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADL", DbType="Int")]
		public System.Nullable<int> MADL
		{
			get
			{
				return this._MADL;
			}
			set
			{
				if ((this._MADL != value))
				{
					if (this._DAILY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADLChanging(value);
					this.SendPropertyChanging();
					this._MADL = value;
					this.SendPropertyChanged("MADL");
					this.OnMADLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHUTIEN", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTHUTIEN
		{
			get
			{
				return this._NGAYTHUTIEN;
			}
			set
			{
				if ((this._NGAYTHUTIEN != value))
				{
					this.OnNGAYTHUTIENChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHUTIEN = value;
					this.SendPropertyChanged("NGAYTHUTIEN");
					this.OnNGAYTHUTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTIEN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SOTIEN
		{
			get
			{
				return this._SOTIEN;
			}
			set
			{
				if ((this._SOTIEN != value))
				{
					this.OnSOTIENChanging(value);
					this.SendPropertyChanging();
					this._SOTIEN = value;
					this.SendPropertyChanged("SOTIEN");
					this.OnSOTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOITHU", DbType="Int")]
		public System.Nullable<int> NGUOITHU
		{
			get
			{
				return this._NGUOITHU;
			}
			set
			{
				if ((this._NGUOITHU != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNGUOITHUChanging(value);
					this.SendPropertyChanging();
					this._NGUOITHU = value;
					this.SendPropertyChanged("NGUOITHU");
					this.OnNGUOITHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAILY_PHIEUTHUTIEN", Storage="_DAILY", ThisKey="MADL", OtherKey="MADL", IsForeignKey=true)]
		public DAILY DAILY
		{
			get
			{
				return this._DAILY.Entity;
			}
			set
			{
				DAILY previousValue = this._DAILY.Entity;
				if (((previousValue != value) 
							|| (this._DAILY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DAILY.Entity = null;
						previousValue.PHIEUTHUTIENs.Remove(this);
					}
					this._DAILY.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHUTIENs.Add(this);
						this._MADL = value.MADL;
					}
					else
					{
						this._MADL = default(Nullable<int>);
					}
					this.SendPropertyChanged("DAILY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUTHUTIEN", Storage="_NHANVIEN", ThisKey="NGUOITHU", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUTHUTIENs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHUTIENs.Add(this);
						this._NGUOITHU = value.MANV;
					}
					else
					{
						this._NGUOITHU = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[vwCHUCVU-NHANVIEN-TAIKHOAN]")]
	public partial class vwCHUCVU_NHANVIEN_TAIKHOAN
	{
		
		private string _TENCHUCVU;
		
		private string _TENNV;
		
		private int _MANV;
		
		private string _TENDANGNHAP;
		
		private string _PASSWORD;
		
		public vwCHUCVU_NHANVIEN_TAIKHOAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCVU", DbType="VarChar(30)")]
		public string TENCHUCVU
		{
			get
			{
				return this._TENCHUCVU;
			}
			set
			{
				if ((this._TENCHUCVU != value))
				{
					this._TENCHUCVU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NChar(10)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this._TENNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int NOT NULL")]
		public int MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this._MANV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDANGNHAP", DbType="NChar(20)")]
		public string TENDANGNHAP
		{
			get
			{
				return this._TENDANGNHAP;
			}
			set
			{
				if ((this._TENDANGNHAP != value))
				{
					this._TENDANGNHAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[vwDAILY-PHIEUTHUTIEN-NHANVIEN]")]
	public partial class vwDAILY_PHIEUTHUTIEN_NHANVIEN
	{
		
		private string _TENDL;
		
		private int _MAPHIEU;
		
		private System.Nullable<int> _MADL;
		
		private System.Nullable<System.DateTime> _NGAYTHUTIEN;
		
		private System.Nullable<decimal> _SOTIEN;
		
		private System.Nullable<int> _NGUOITHU;
		
		private string _TENNV;
		
		public vwDAILY_PHIEUTHUTIEN_NHANVIEN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDL", DbType="NVarChar(50)")]
		public string TENDL
		{
			get
			{
				return this._TENDL;
			}
			set
			{
				if ((this._TENDL != value))
				{
					this._TENDL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEU", DbType="Int NOT NULL")]
		public int MAPHIEU
		{
			get
			{
				return this._MAPHIEU;
			}
			set
			{
				if ((this._MAPHIEU != value))
				{
					this._MAPHIEU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADL", DbType="Int")]
		public System.Nullable<int> MADL
		{
			get
			{
				return this._MADL;
			}
			set
			{
				if ((this._MADL != value))
				{
					this._MADL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHUTIEN", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTHUTIEN
		{
			get
			{
				return this._NGAYTHUTIEN;
			}
			set
			{
				if ((this._NGAYTHUTIEN != value))
				{
					this._NGAYTHUTIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOTIEN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SOTIEN
		{
			get
			{
				return this._SOTIEN;
			}
			set
			{
				if ((this._SOTIEN != value))
				{
					this._SOTIEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOITHU", DbType="Int")]
		public System.Nullable<int> NGUOITHU
		{
			get
			{
				return this._NGUOITHU;
			}
			set
			{
				if ((this._NGUOITHU != value))
				{
					this._NGUOITHU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NChar(10)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this._TENNV = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[vw-SEARCH-PHIEUXUATHANG]")]
	public partial class vw_SEARCH_PHIEUXUATHANG
	{
		
		private string _TENHANG;
		
		private string _DVT;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private string _TENQUAN;
		
		private string _TENDL;
		
		public vw_SEARCH_PHIEUXUATHANG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHANG", DbType="NVarChar(50)")]
		public string TENHANG
		{
			get
			{
				return this._TENHANG;
			}
			set
			{
				if ((this._TENHANG != value))
				{
					this._TENHANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(50)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this._DVT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this._SOLUONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this._NGAYLAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENQUAN", DbType="NVarChar(50)")]
		public string TENQUAN
		{
			get
			{
				return this._TENQUAN;
			}
			set
			{
				if ((this._TENQUAN != value))
				{
					this._TENQUAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDL", DbType="NVarChar(50)")]
		public string TENDL
		{
			get
			{
				return this._TENDL;
			}
			set
			{
				if ((this._TENDL != value))
				{
					this._TENDL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[vwDAILY-LOAIDL-QUAN]")]
	public partial class vwDAILY_LOAIDL_QUAN
	{
		
		private int _MADL;
		
		private string _TENDL;
		
		private string _DIENTHOAI;
		
		private string _DIACHI;
		
		private System.Nullable<System.DateTime> _NGAYTIEPNHAN;
		
		private System.Nullable<decimal> _SONO;
		
		private System.Nullable<int> _TINHTRANG;
		
		private string _TENLOAI;
		
		private string _TENQUAN;
		
		private System.Nullable<int> _MAQUAN;
		
		private System.Nullable<int> _LOAIDL;
		
		public vwDAILY_LOAIDL_QUAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADL", DbType="Int NOT NULL")]
		public int MADL
		{
			get
			{
				return this._MADL;
			}
			set
			{
				if ((this._MADL != value))
				{
					this._MADL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDL", DbType="NVarChar(50)")]
		public string TENDL
		{
			get
			{
				return this._TENDL;
			}
			set
			{
				if ((this._TENDL != value))
				{
					this._TENDL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(50)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this._DIENTHOAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this._DIACHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTIEPNHAN", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTIEPNHAN
		{
			get
			{
				return this._NGAYTIEPNHAN;
			}
			set
			{
				if ((this._NGAYTIEPNHAN != value))
				{
					this._NGAYTIEPNHAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SONO
		{
			get
			{
				return this._SONO;
			}
			set
			{
				if ((this._SONO != value))
				{
					this._SONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="Int")]
		public System.Nullable<int> TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this._TINHTRANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(10)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this._TENLOAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENQUAN", DbType="NVarChar(50)")]
		public string TENQUAN
		{
			get
			{
				return this._TENQUAN;
			}
			set
			{
				if ((this._TENQUAN != value))
				{
					this._TENQUAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAQUAN", DbType="Int")]
		public System.Nullable<int> MAQUAN
		{
			get
			{
				return this._MAQUAN;
			}
			set
			{
				if ((this._MAQUAN != value))
				{
					this._MAQUAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIDL", DbType="Int")]
		public System.Nullable<int> LOAIDL
		{
			get
			{
				return this._LOAIDL;
			}
			set
			{
				if ((this._LOAIDL != value))
				{
					this._LOAIDL = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
